Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "D:\venv\zika3\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "D:\venv\zika3\lib\site-packages\django\core\management\__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\venv\zika3\lib\site-packages\django\core\management\base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "D:\venv\zika3\lib\site-packages\django\core\management\base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "C:\Python35\Lib\contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "D:\Repositories\zikab\website\apps\home\management\commands\load_sim_data.py", line 29, in handle
    sim = Simulation.objects.get(id=sim_id)
  File "D:\venv\zika3\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\venv\zika3\lib\site-packages\django\db\models\query.py", line 385, in get
    self.model._meta.object_name
website.apps.home.models.DoesNotExist: Simulation matching query does not exist.
chunks
    self.seek(0)
  File "D:\venv\zika3\lib\site-packages\django\core\files\utils.py", line 23, in <lambda>
    seek = property(lambda self: self.file.seek)
  File "D:\venv\zika3\lib\site-packages\django\db\models\fields\files.py", line 51, in _get_file
    self._file = self.storage.open(self.name, 'rb')
  File "D:\venv\zika3\lib\site-packages\django\core\files\storage.py", line 38, in open
    return self._open(name, mode)
  File "D:\venv\zika3\lib\site-packages\django\core\files\storage.py", line 300, in _open
    return File(open(self.path(name), mode))
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Repositories\\zikab\\website\\media\\simulation_files\\fixed_data_2.csv'
